# Generated by Django 3.2.5 on 2022-05-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='startBid',
            field=models.IntegerField(max_length=9999),
        ),
    ]
