# Generated by Django 4.0.4 on 2022-05-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auctionlisting_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='startBid',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
